"""
Django settings for aitpmsys project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x$$8ju=6y2=d$%nqq4@e#zqc9*$a2#5ww-rfge&d1ovn&fy6z&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'linechatbot',
    'allauth',
    'allauth.account',
    'django.contrib.sites',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.line',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'aitpmsys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'aitteachingsys','templates')], #20230721 add by 11157017 #主要設定的是系統的templates資料夾，app的資料夾涵蓋在app設定中，因此無須另外設定也抓地到。
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aitpmsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 20230721 mark by 11157017 start
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        # 20230721 mark by 11157017 end
        # 20230721 add by 11157017 start
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'aitpmsysdb',
        'USER': 'sys_superuser',
        'PASSWORD': 'recast203',
        'HOST': 'localhost',
        'POST': '5432',
        # 20230721 add by 11157017 end
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')
MEDIA_TEACHER=os.path.join(BASE_DIR,'teacherapp/static/media/')  #/root/aitteachingsys/teacherapp/static/media/
MEDIA_STUDENT=os.path.join(BASE_DIR,'studentapp/static/media/')  #/root/aitteachingsys/studentapp/static/media/

STATICILES_DIRS = [
    os.path.join(BASE_DIR,'static'),
    os.path.join(BASE_DIR,'aitteachingsys','static'),
    os.path.join(BASE_DIR,'teacherapp','static'),  #/root/aitteachingsys/teacherapp/static
    os.path.join(BASE_DIR,'studentapp','static'),  #/root/aitteachingsys/studentapp/static
]

NGROK_INFO='https://aitcourse.ntou.edu.tw:15480/' #20230810 add by 11157017

#LINEBOT SETTING
#ChatBOT
LINE_CHANNEL_ACCESS_TOKEN = '02qeHOzIhsQuDxYd4fJJh0RFOUdyaFg2Tu/RA9p+LVDpDYNC8B3AuAseHaDD+ZIzZ71rBkH9EJ4rqT+JBMMXJ2X0xTKaee7G+C9b54dZZB74GIvOXiBY/Vxj8FKfnODUsoDu17Lj4HKXTOIByAw66AdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '443e1314011990d61d4ffe1c10b85aba'
#LINE Login
LINE_LOGIN_CHANNEL_ID = '2003931347'
LINE_LOGIN_CHANNEL_SECRET = '1f00729f7994b38121b642afa1b3d228'


# SMTP Configuration
# 有需要再開放，開放時需要考慮流量
# 可以換成另外一個mail : pmsys.aitlab@gmail.com，只是需要申請應用程式密碼
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  #SMTP伺服器
# EMAIL_PORT = 587               #TLS通訊埠號
# EMAIL_USE_TLS = True           #開啟TLS(傳輸層安全性)
# EMAIL_HOST_USER = 'service.aitlab@gmail.com'  #寄件者電子郵件
# EMAIL_HOST_PASSWORD = 'hthdpzfveokubdvw'  #Gmail應用程式的密碼
