# Generated by Django 4.2.11 on 2024-03-05 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineBindList',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('lineid', models.CharField(max_length=35, unique=True)),
                ('ac', models.CharField(max_length=20, null=True)),
                ('pw', models.CharField(max_length=32, null=True)),
                ('identity', models.IntegerField(default=0, null=True)),
                ('moditime', models.DateTimeField(default=datetime.datetime(2024, 3, 6, 0, 4, 54, 937042))),
            ],
        ),
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('moditime', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.linebindlist')),
            ],
        ),
    ]
